package com.obsidianbackup.enterprise.auth

import org.slf4j.LoggerFactory
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.security.core.Authentication
import org.springframework.security.saml2.provider.service.authentication.Saml2AuthenticatedPrincipal
import org.springframework.security.saml2.provider.service.authentication.Saml2Authentication
import org.springframework.stereotype.Service

/**
 * SAML 2.0 SSO authentication provider for ObsidianBackup Enterprise.
 *
 * Activated only when `application.saml.enabled=true` is set in application.properties
 * or environment variables. When disabled, the enterprise backend uses JWT auth only.
 *
 * ## IdP Setup (one-time per customer)
 *
 * 1. Register the service provider (SP) with your Identity Provider (IdP):
 *    - SP Entity ID:          `https://<your-domain>/saml2/service-provider-metadata/obsidianbackup`
 *    - ACS URL (POST):        `https://<your-domain>/login/saml2/sso/obsidianbackup`
 *    - SP Certificate:        generated by Spring Security SAML2 auto-configuration
 *
 * 2. Obtain from your IdP:
 *    - IdP metadata URL or XML file
 *    - Attribute name that carries the user's email (often `email` or `urn:oid:0.9.2342...`)
 *    - Attribute name for role/group membership (often `groups` or `memberOf`)
 *
 * 3. Configure `application.properties` (or environment variables):
 *    ```
 *    application.saml.enabled=true
 *    spring.security.saml2.relyingparty.registration.obsidianbackup.identityprovider.metadata-uri=https://your-idp.example.com/metadata
 *    spring.security.saml2.relyingparty.registration.obsidianbackup.identityprovider.entity-id=https://your-idp.example.com
 *    obsidian.saml.email-attribute=email
 *    obsidian.saml.role-attribute=groups
 *    ```
 *
 * ## Authentication Flow
 *
 * 1. User visits `/saml/login` → [initiateSamlLogin] redirects to IdP
 * 2. IdP authenticates user and POSTs SAML Response to ACS URL
 * 3. Spring Security SAML2 validates the response and calls [handleSamlResponse]
 * 4. [validateAssertion] verifies required attributes are present
 * 5. [resolveUserFromAssertion] looks up or creates the local user record
 * 6. JWT token issued and returned to the web client
 */
@Service
@ConditionalOnProperty(name = ["application.saml.enabled"], havingValue = "true")
class SamlAuthProvider {

    private val logger = LoggerFactory.getLogger(SamlAuthProvider::class.java)

    /**
     * Called after Spring Security successfully validates the incoming SAML Response.
     * Extracts identity information from the assertion and returns a local user identity.
     *
     * @param authentication The SAML2Authentication object produced by Spring Security.
     * @return A [SamlUserInfo] containing email, display name, and roles extracted from the assertion.
     * @throws SamlAuthException if required attributes are missing or the assertion is invalid.
     */
    fun handleSamlResponse(authentication: Authentication): SamlUserInfo {
        val samlAuth = authentication as? Saml2Authentication
            ?: throw SamlAuthException("Expected Saml2Authentication, got ${authentication::class.simpleName}")

        val principal = samlAuth.principal as? Saml2AuthenticatedPrincipal
            ?: throw SamlAuthException("Unexpected principal type: ${samlAuth.principal::class.simpleName}")

        logger.info("SAML assertion received for name={}", principal.name)

        return validateAssertion(principal)
    }

    /**
     * Validate that the SAML assertion contains the required attributes.
     *
     * Required attributes:
     * - Email address (attribute name configured via `obsidian.saml.email-attribute`)
     * - At minimum one role/group (attribute name via `obsidian.saml.role-attribute`)
     *
     * TODO("SAML: inject @Value(\"${obsidian.saml.email-attribute}\") for the attribute name")
     * TODO("SAML: inject @Value(\"${obsidian.saml.role-attribute}\") for the role attribute name")
     *
     * @param principal Authenticated SAML2 principal from Spring Security.
     * @return Extracted [SamlUserInfo].
     * @throws SamlAuthException if required attributes are absent.
     */
    fun validateAssertion(principal: Saml2AuthenticatedPrincipal): SamlUserInfo {
        // TODO("SAML: replace hardcoded attribute names with @Value-injected properties")
        val emailAttribute = "email"
        val roleAttribute  = "groups"

        val email = principal.getFirstAttribute<String>(emailAttribute)
            ?: throw SamlAuthException(
                "SAML assertion missing required attribute '$emailAttribute'. " +
                "Check IdP attribute mapping configuration."
            )

        val roles = principal.getAttribute<String>(roleAttribute) ?: emptyList<String>()

        logger.debug("SAML assertion validated: email={}, roles={}", email, roles)

        return SamlUserInfo(
            nameId  = principal.name,
            email   = email,
            roles   = roles,
            attributes = principal.attributes
        )
    }

    /**
     * Look up an existing user by email or provision a new account from the SAML assertion.
     *
     * TODO("SAML: inject UserRepository and call findByEmail(userInfo.email)")
     * TODO("SAML: if user not found and JIT provisioning is enabled, create the account")
     * TODO("SAML: map IdP roles in userInfo.roles to enterprise FeatureTier / RBAC roles")
     *
     * @param userInfo Verified user identity from [validateAssertion].
     * @return The local user UUID.
     * @throws SamlAuthException if the user cannot be found and JIT provisioning is disabled.
     */
    fun resolveUserFromAssertion(userInfo: SamlUserInfo): java.util.UUID {
        TODO(
            "SAML: implement user lookup/provisioning. " +
            "Inject UserRepository, call findByEmail(userInfo.email). " +
            "If not found and JIT_PROVISIONING=true, create the account and assign roles."
        )
    }

    /**
     * Build the redirect URL that initiates SP-initiated SAML login.
     *
     * Spring Security handles the actual AuthnRequest generation and redirect via
     * `/saml2/authenticate/{registrationId}`. This helper exists so controllers can
     * redirect users to the correct IdP without hardcoding the registration ID.
     *
     * TODO("SAML: inject @Value(\"${spring.security.saml2.relyingparty.registration.*}\") registrationId")
     *
     * @param registrationId Spring Security SAML2 registration ID (e.g. "obsidianbackup").
     * @return The URL to redirect the browser to in order to start the SAML flow.
     */
    fun buildSamlLoginUrl(registrationId: String = "obsidianbackup"): String {
        return "/saml2/authenticate/$registrationId"
    }
}

/** Structured user identity extracted from a validated SAML assertion. */
data class SamlUserInfo(
    val nameId: String,
    val email: String,
    val roles: List<String>,
    val attributes: Map<String, List<Any>>
)

/** Thrown when SAML assertion validation fails or required attributes are missing. */
class SamlAuthException(message: String, cause: Throwable? = null) : RuntimeException(message, cause)
